import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthSession from "./_component/AuthSession";
import "./globals.css";
import RQProvider from "./_component/RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthSession>
          <RQProvider>{children}</RQProvider>
        </AuthSession>
      </body>
    </html>
  );
}
